######################################################################
# Automatically generated by qmake (3.0) Sat Jun 28 20:38:23 2014
######################################################################

TEMPLATE = app
TARGET = fishnet
#CONFIG += debug
INCLUDEPATH += .

QMAKE_CXXFLAGS += -std=c++11

# Input
HEADERS += fishnet.hpp window.hpp
SOURCES += fishnet.cpp window.cpp
